### ISSUE TITLE
Mandelbrot demo: show the image

### ISSUE THREAD

**Issue by certik** [lfortran/lcompilers_frontend#11]
TODO:

* [x] Get the image out of Fortran and into JavaScript using the approach described at: https://gitlab.com/lfortran/lfortran/-/issues/761#note_1056724358
* [x] Show the image on a canvas from JavaScript

Old:

Here is a code that compiles to WAT at [dev.lfortran.org](https://dev.lfortran.org): https://gitlab.com/lfortran/lfortran/-/issues/702#note_1059822597, but the execution window says:
```
ERROR: The code could not be executed. Either there is a runtime error or there is an issue at our end.
```

So we need to investigate what is going on.

**Comment by Shaikh-Ubaid** [comment]
It seems the initial example code failed due to insufficient memory. We recently increased the memory limit in https://github.com/lfortran/lfortran/pull/126. Probably, the current `lfortran.wasm` at [dev.lfortran.org](dev.lfortran.org) was compiled prior to the increase in memory and I guess, therefore the error. I will update the `lfortran.wasm` (and `lfortran.js`) at [dev.lfortran.org](dev.lfortran.org) with the latest one soon.

**Comment by certik** [comment]
@Shaikh-Ubaid I think that's right. Even the `pow` that we fixed didn't work, so you can see I worked around it too. These are both quite easy to fix.

**Comment by Shaikh-Ubaid** [comment]
Please, could someone possibly share if this issue is complete?

**Comment by certik** [comment]
This is fixed! Thank you so much @Shaikh-Ubaid for implementing it. Here is how it looks like for me now at dev.lfortran.org:

<img width="1520" alt="Screen Shot 2022-08-14 at 8 50 42 AM" src="https://user-images.githubusercontent.com/20568/184528794-595768f8-49ea-41ca-b8f1-f895605339ee.png">
